version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app-backend
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - DB_NAME=ultracommerce
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db
      - JWT_SECRET=0u9dgsjhiofewgf89dsvh083gt45in987gdsvu9b
    restart: always
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app-frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
